name: Build and Push Docker Image to GHCR

# Run this workflow manually from the Actions tab or on pushes to the main branch
on:
  push:
    branches: [ "main" ] # Or your default branch name if different
  workflow_dispatch: # Allows manual triggering

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # <<< IMPORTANT: Permission to write to GHCR

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }} # Your GitHub username/org
        password: ${{ secrets.GITHUB_TOKEN }}   # <<< Use the automatically provided GitHub token

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        # <<< CHANGE: Tag format for GHCR
        tags: ghcr.io/${{ github.repository_owner }}/nerfstudio-runner:latest
        # Example tag: ghcr.io/gipsyking5/nerfstudio-runner:latest
